pages:
  image: alpine
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - pip install Flask-Sphinx-Themes
  - cd docs
  - ./build-html.sh
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
    changes:
      - docs/**
