version: "{branch}-{build}"
cache:
    - '%LOCALAPPDATA%\pip\Cache'
build: off

skip_tags: true

shallow_clone: true
clone_depth: 100

environment:
    global:
        WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor\compiler.cmd'

    matrix:
        - TOXENV: 'py27-{noaccel,accel-win,streams}'
          TOXPYTHON: C:\Python27\python.exe
          PYTHON_HOME: C:\Python27
          PYTHON_VERSION: '2.7'
          PYTHON_ARCH: '32'

        - TOXENV: 'py33-{noaccel,accel-win,streams}'
          TOXPYTHON: C:\Python33\python.exe
          PYTHON_HOME: C:\Python33
          PYTHON_VERSION: '3.3'
          PYTHON_ARCH: '32'

        - TOXENV: 'py34-{noaccel,accel-win,streams}'
          TOXPYTHON: C:\Python34\python.exe
          PYTHON_HOME: C:\Python34
          PYTHON_VERSION: '3.4'
          PYTHON_ARCH: '32'

        - TOXENV: 'py35-{noaccel,accel-win,streams}'
          TOXPYTHON: C:\Python35\python.exe
          PYTHON_HOME: C:\Python35
          PYTHON_VERSION: '3.5'
          PYTHON_ARCH: '32'

init:
    - ps: echo $env:TOXENV
    - ps: ls C:\Python*

install:
    - '%TOXPYTHON% --version'
    - '%PYTHON_HOME%\Scripts\pip --version'
    - '%TOXPYTHON% -m pip install --egg tox'
    - '%PYTHON_HOME%\Scripts\tox --version'

test_script:
    - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'

on_failure:
    - ps: dir "env:"
    - ps: get-content .tox\*\log\*
